// Writes the app's icons into a TypeScript file (ADR 0008): only the icons listed here, taken
// from Iconify's Lucide set at build time, so the app never calls the Iconify API and works
// offline. Add an icon's name below and run `pnpm icons`. Icons from another set must match
// Lucide's look (24 px grid, 2 px round strokes).
import { readFileSync, writeFileSync } from 'node:fs';

const ICONS = [
  'app-window',
  'arrow-down-left',
  'arrow-down-to-line',
  'arrow-left-to-line',
  'arrow-right-to-line',
  'arrow-up-right',
  'arrow-up-to-line',
  'check',
  'box',
  'brick-wall',
  'building-2',
  'chevron-down',
  'chevron-right',
  'door-open',
  'ellipsis',
  'eye',
  'eye-off',
  'file-down',
  'file-plus',
  'flip-horizontal-2',
  'folder-open',
  'languages',
  'layers',
  'library-big',
  'maximize-2',
  'merge',
  'minimize-2',
  'minus',
  'moon',
  'mouse-pointer-2',
  'move-diagonal-2',
  'move-horizontal',
  'move-vertical',
  'panel-right',
  'pencil',
  'plus',
  'redo-2',
  'rotate-ccw',
  'ruler',
  'save',
  'save-all',
  'sheet',
  'slash',
  'split',
  'square',
  'square-dashed',
  'sun',
  'sun-moon',
  'trash-2',
  'triangle-alert',
  'undo-2',
  'x',
];

const set = JSON.parse(readFileSync('node_modules/@iconify-json/lucide/icons.json', 'utf8'));
const out = {};
for (const name of ICONS) {
  const icon = set.icons[name] ?? set.icons[set.aliases?.[name]?.parent];
  if (!icon) throw new Error(`Lucide has no icon "${name}"`);
  out[name] = icon.body;
}
const lines = Object.entries(out).map(([k, v]) => `  '${k}': ${JSON.stringify(v)},`);
writeFileSync(
  'projects/web/src/app/shell/icons.generated.ts',
  `// Generated by scripts/build-icons.mjs from Iconify's Lucide set (ISC licence). Do not edit.\n` +
    `export const ICONS = {\n${lines.join('\n')}\n} as const;\n\nexport type IconName = keyof typeof ICONS;\n`,
);
console.log(`icons: ${ICONS.length} written`);
